# .github/workflows/build-and-deploy.yml

name: Node.js CI

on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to build"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-node@v3
        with:
          # update the Node version to meet your needs
          node-version: 19
          cache: npm

      - name: Build
        run: |
          npm install gray-matter
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll

      - name: Deploy
        # configure an external GitHub Pages deploy workflow here
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: out
