name: Update Telsa data

on:
  schedule:
    # check every day for the rest of the week at 6:38 UTC
    - cron: 38 6 * * *
  workflow_dispatch:

defaults:
  run:
    working-directory: lib

jobs:
  update-tesla-data:
    name: Update MD3 data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new-commit-sha: ${{ steps.head_commit.outputs.commit_sha }}
      updated: ${{ steps.commit.outputs.pushed }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install beautifulsoup4
          python -m pip install selenium
      - name: Run MDS scrap script
        run: python tesla-scrap.py models mds
      - name: Run MD3 scrap script
        run: python tesla-scrap.py model3 md3
      - name: Run MDX scrap script
        run: python tesla-scrap.py modelx mdx
      - name: Run MDY scrap script
        run: python tesla-scrap.py modely mdy
      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
      - id: head_commit
        run: echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  build:
    if: needs.update-tesla-data.outputs.updated == 'true'
    permissions:
      contents: write
    uses: Nyc0/nextjs-blog/.github/workflows/build-and-deploy-blog-following-update.yml@main
    needs: [update-tesla-data]
    with:
      ref: ${{ needs.update-tesla-data.outputs.new-commit-sha }}
    #Secrets would not be known by the reusable workflow, they either have to be explicite or inherit https://docs.github.com/en/actions/using-workflows/reusing-workflows 
    secrets:
      ftpPwd: ${{ secrets.FTP_PASSWORD }}
