name: Update NVC data

on:
  schedule:
    # Remember the time is UTC https://www.worldtimebuddy.com/
    # check every 10 minutes on Monday in the update window. Assumption that update window is 2 to 4 pm EDT
    - cron: 3/10 18-20 * * 1
    # check every hour on Monday outside the update window from 12:38 to 7:38 pm EDT
    - cron: 38 16-18,20,21-23 * * 1
    # check every day for the rest of the week at 4:38 am
    - cron: 38 8 * * 0,2-6
  workflow_dispatch:

defaults:
  run:
    working-directory: lib

jobs:
  update-nvc-data:
    name: Update NVC data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new-commit-sha: ${{ steps.head_commit.outputs.commit_sha }}
      updated: ${{ steps.commit.outputs.pushed }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install requests
          python -m pip install beautifulsoup4
      - name: Run script
        run: python nvc-scrap.py
      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
      - id: head_commit
        run: echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  build:
    if: needs.update-nvc-data.outputs.updated == 'true'
    permissions:
      contents: write
    uses: Nyc0/nextjs-blog/.github/workflows/build-and-deploy-blog-following-update.yml@main
    needs: [update-nvc-data]
    with:
      ref: ${{ needs.update-nvc-data.outputs.new-commit-sha }}
